[package]
name = "RandMon"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
